# Generated by Django 4.0.6 on 2022-07-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('name_header', models.CharField(max_length=250, verbose_name='Повна назва')),
                ('img_project', models.ImageField(upload_to='images/', verbose_name='Фото проекту')),
                ('name_project', models.CharField(max_length=50, verbose_name='Назва проекту')),
                ('info_about', models.TextField(verbose_name='Інформація про проект')),
                ('order', models.CharField(max_length=100, verbose_name='Замовник')),
                ('adress', models.CharField(max_length=50, verbose_name='Адреса')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекти',
            },
        ),
    ]
