# Generated by Django 4.0.6 on 2022-08-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterModelOptions(
            name='app',
            options={},
        ),
        migrations.AlterField(
            model_name='app',
            name='adress',
            field=models.CharField(max_length=100, verbose_name='Адреса'),
        ),
    ]
