# Generated by Django 4.0.6 on 2022-08-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_meta_alter_empdetails_email_alter_empdetails_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекти'},
        ),
        migrations.AlterModelOptions(
            name='empdetails',
            options={'verbose_name': 'Користувач', 'verbose_name_plural': 'Користувачі'},
        ),
        migrations.DeleteModel(
            name='Meta',
        ),
    ]
