# Generated by Django 4.0.6 on 2022-08-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_app_options_alter_empdetails_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmpDetails',
            new_name='User',
        ),
    ]
