# Generated by Django 4.0.6 on 2022-08-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('short_info', models.CharField(max_length=50, verbose_name='Короткий опис')),
                ('img_project', models.ImageField(upload_to='images/', verbose_name='Фото проекту')),
            ],
            options={
                'verbose_name': 'Коротка інформація',
                'verbose_name_plural': 'Список всіх проектів',
            },
        ),
    ]
