# Generated by Django 4.0.6 on 2022-08-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_projects_short_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='eng_name',
            field=models.CharField(default='name', max_length=100, verbose_name='Name'),
        ),
    ]
