# Generated by Django 4.0.6 on 2022-08-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_projects_eng_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='eng_name',
            field=models.CharField(default='#', max_length=100, verbose_name='Name'),
        ),
    ]
